import React from 'react'

import './globals.css'
import { Inter } from 'next/font/google'
import CommonLayout from '../components/layout/CommonLayout'
import Header from '../components/layout/Header'
import Footer from '../components/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-white">
      <Header/>
        {children}
        <Footer/>
        </body>
      
    </html>
  )
}
